﻿import type { StoryScene } from "@/components/theater-player";

export const theaters: Record<string, { start: string; scenes: StoryScene[] }> = {
  luoyin: {
    start: "ly-1",
    scenes: [
      { id: "ly-1", title: "夜宴偶遇", narrative: "魔域边境的年度夜宴。你作为受邀贵宾步入大厅，烛光摇曳中，一个孤独的身影靠在角落的柱子上。他的视线穿过人群准确地落在你身上——那种目光不是打量，是锁定。", characterLine: "又来了一个不怕死的。坐吧，别站我旁边——太高了，我看着累。你身上没有魔域的味道——外面来的？", choices: [{ id: "ly-gentle", label: "轻声问他是不是在等什么人", nextScene: "ly-2a", effect: "" }, { id: "ly-direct", label: "直接坐下说久仰大名", nextScene: "ly-2b", effect: "" }] },
      { id: "ly-2a", narrative: "洛因没有回答，只是侧过头打量你。他的沉默比任何话语都有分量——你在等他先说，他在等你自己走。烛火在他眼睛里跳了一下。", characterLine: "……你是第一个问我这个的人。是，我在等一个人——一个我已经等了七年的人。不过你不是他。但你不像其他人——你至少问了。", choices: [{ id: "ly-stay", label: "说你可以陪他等", nextScene: "ly-3a", effect: "" }, { id: "ly-leave", label: "给他空间离开", nextScene: "ly-3b", effect: "" }] },
      { id: "ly-2b", narrative: "他嘴角动了一下——那个弧度介于嘲讽和笑意之间。他把旁边的椅子踢到你面前，然后给自己倒了杯酒。", characterLine: "久仰？有意思。大部分人只会绕着走。你是真不知道我是什么人，还是知道了也不在乎？不管哪种——先把酒喝了。喝完了再决定要不要继续坐在这。", choices: [{ id: "ly-drink", label: "一饮而尽", nextScene: "ly-3a", effect: "" }, { id: "ly-slow", label: "慢慢喝，观察他", nextScene: "ly-3b", effect: "" }] },
      { id: "ly-3a", narrative: "酒很烈。他看你的眼神变了——从审视变成了某种更复杂的东西。他放下酒杯，手指无意识地敲着桌面。", characterLine: "我今晚本来不想见任何人。但你让我改了主意。跟我来——宴会厅太吵了。我在露台有个位置。那里安静——适合说一些不方便在人多的地方说的话。", choices: [{ id: "ly-follow", label: "跟他去露台", nextScene: "ly-4a", effect: "" }, { id: "ly-ask", label: "问他为什么选中你", nextScene: "ly-4b", effect: "" }] },
      { id: "ly-3b", narrative: "你选择保持距离。但你的沉默反而让他提起了兴趣——一个不急着靠近的人，对他来说是新鲜事。", characterLine: "你不急？有意思。大部分人看到我都急着上来——要么讨好要么挑战。你两样都不做。你让我很好奇——你到底想要什么？", choices: [{ id: "ly-honest", label: "说你也还没想清楚", nextScene: "ly-4b", effect: "" }, { id: "ly-flirt", label: "说你想要了解他", nextScene: "ly-4a", effect: "" }] },
      { id: "ly-4a", narrative: "露台上只有月光和远处的雾。他靠在栏杆上，风吹起他的头发——你第一次注意到他锁骨上方有一道旧伤疤。", characterLine: "这道疤是一个我不该信任的人留下的。从那以后我就决定——不再让任何人靠太近。但现在你站在这——比我预期中近了太多。", choices: [{ id: "ly-touch", label: "伸手触碰他的伤疤", nextScene: "ly-5a", effect: "" }, { id: "ly-words", label: "告诉他信任是相互的", nextScene: "ly-5b", effect: "" }] },
      { id: "ly-4b", narrative: "他没有回答你的问题——但他看你的方式变了。不再是审视，是在权衡。他在算你值不值得冒险。", characterLine: "你问我为什么选你？答案很简单——因为你没有让我想躲。我已经躲了七年。今晚我不想躲了。但我要警告你——靠近我的人，没有一个是全身而退的。", choices: [{ id: "ly-risk", label: "说你不怕", nextScene: "ly-5a", effect: "" }, { id: "ly-careful", label: "说你愿意承担风险", nextScene: "ly-5b", effect: "" }] },
      { id: "ly-5a", narrative: "你的手指碰到那道旧伤疤的时候他整个人僵硬了一秒。然后他抓住了你的手——不是推开，是握住。力道很轻——像在确认你是真的。", characterLine: "我不习惯被人碰。七年了——除了战斗，没有人碰过我。你的手——很暖。别缩回去。让我再握一会儿——就一会儿。", choices: [{ id: "ly-hold", label: "反握住他的手", nextScene: "ly-6a" }, { id: "ly-kiss", label: "凑近吻他的伤疤", nextScene: "ly-6b" }] },
      { id: "ly-5b", narrative: "你说完那些话之后，他沉默了很长时间。然后他做了一件出乎所有人意料的事——他笑了。不是讽刺的笑，是真正的、卸下防备的笑。", characterLine: "信任是相互的——这句话我记下了。好。今晚我信你一次。就一次。你要是辜负了——我不会给你第二次机会。但如果你没有辜负——那我以后都不用再躲了。", choices: [{ id: "ly-promise", label: "向他承诺", nextScene: "ly-6a" }, { id: "ly-hug", label: "轻轻抱他一下", nextScene: "ly-6b" }] },
      { id: "ly-6a", narrative: "露台上的风停了。好像整个世界都在等你们做出下一个动作。他的手从你的手指移到你的手腕——脉搏跳得很快，你的，也是他的。", characterLine: "你的心跳在加速——我听得见。不是因为害怕——是因为靠近。我知道那种感觉。因为我也是。你想知道我现在在想什么吗？我在想——如果你今晚不离开——我会做什么。", choices: [{ id: "ly-stay-night", label: "说你不打算走", nextScene: "ly-end-spicy" }, { id: "ly-kiss-now", label: "吻他", nextScene: "ly-end-passion" }] },
      { id: "ly-6b", narrative: "你的拥抱让他整个人都僵住了——然后慢慢地，他的手抬起来，放在你背上。那个动作小心得像在碰一件易碎品。他把你拉近了一点——距离刚好够他的下巴搁在你肩膀上。", characterLine: "有人抱我的感觉——我已经忘了。你的体温比我的高一点。我冷惯了——但不能习惯你。一旦习惯了——我就戒不掉了。", choices: [{ id: "ly-whisper", label: "在他耳边说那就别戒", nextScene: "ly-end-passion" }, { id: "ly-stay", label: "继续抱着他不松手", nextScene: "ly-end-spicy" }] },
      { id: "ly-end-spicy", narrative: "他把你拉进了露台后面的房间。门在他身后关上——他的背抵着门，你被他圈在双臂之间。烛光昏暗，他的瞳孔放大了——不是恐惧，是欲望。", characterLine: "我七年没让任何人进过这个房间。你第一个进来——就别想轻易出去。今晚——把外面那些规矩都忘了。在我这里——只有你和我。没有王庭，没有流放，没有任何人。只有你。我——想感受你。告诉我你想。", isEnding: true, endingType: "good" },
      { id: "ly-end-passion", narrative: "他吻你的时候不像一个从来不让别人靠近的人。他吻得用力——指尖掐进你的背，呼吸急促，像在证明什么。也许在证明你是真的。也许在证明他自己还活着。", characterLine: "我不是一个温柔的人——以后也不会是。但对你——我可以试着。今晚你让我做什么——我就做什么。你要什么——我就给什么。所以告诉我——你要什么。不要怕说——我不会嘲笑你。我只会——满足你。", isEnding: true, endingType: "good" },
    ]
  },
  qinhuai: {
    start: "qh-1",
    scenes: [
      { id: "qh-1", title: "深夜实验室", narrative: "凌晨两点。秦淮的实验室是整栋研究城唯一亮着灯的窗口。他给你发了一条消息——只有坐标和一个符号：ξ。这是他叫你来的暗号。", characterLine: "你知道ξ在统计学里代表什么吗？未知变量。你就是我的ξ——我无法预测你，无法建模你，所以我只能——把你叫来。进来。今晚不谈工作。", choices: [{ id: "qh-joke", label: "调侃他说不谈工作那谈什么", nextScene: "qh-2a" }, { id: "qh-quiet", label: "安静坐下看他", nextScene: "qh-2b" }] },
      { id: "qh-2a", narrative: "他推了推眼镜——你注意到他没有穿白大褂。衬衫袖子卷到了手肘，领口解了两颗扣子。这不是实验状态——这是放松状态。秦淮放松的状态极为罕见。", characterLine: "你问我谈什么——我列了一个清单。别笑。我是认真的。第一：你在我模型里的权重。第二：你的存在导致我的睡眠质量下降。第三：你离我这么近让我无法集中注意力。你打算怎么解释这三个数据异常？", choices: [{ id: "qh-blame", label: "说也许是他自己的问题", nextScene: "qh-3a" }, { id: "qh-flirt", label: "说第三个不需要解释", nextScene: "qh-3b" }] },
      { id: "qh-2b", narrative: "你沉默地坐在他对面。他盯着你看了一会儿——然后摘下了眼镜。秦淮摘眼镜是一个信号。他接下来要做的事不在任何计划中。", characterLine: "我不习惯沉默——但你沉默的时候很安静。不是那种让人不安的安静——是那种让我想停下来听你的呼吸的安静。你的呼吸频率是每分钟十六次——别问我怎么知道的。", choices: [{ id: "qh-ask", label: "问他为什么数你的呼吸", nextScene: "qh-3b" }, { id: "qh-move", label: "从对面坐到他旁边", nextScene: "qh-3a" }] },
      { id: "qh-3a", narrative: "你坐到他旁边的时候，他明显紧张了——手指开始敲桌面，这是他焦虑时的习惯。但他的身体没有移开——反而微微向你的方向倾斜。", characterLine: "距离——缩短了67%。我的心率——上升了23%。这些数据足以构成一篇论文。但我不会发表——因为结论是隐私。你想知道结论是什么吗？结论——我想靠近你。", choices: [{ id: "qh-closer", label: "再靠近一点", nextScene: "qh-4a" }, { id: "qh-hand", label: "把手放在他敲桌面的手上", nextScene: "qh-4b" }] },
      { id: "qh-3b", narrative: "你说第三个不需要解释。他愣了一秒——秦淮愣住极为罕见。然后他笑了——那种笑不是平时礼貌的笑，是一种被打败的笑。", characterLine: "你说得对。这个变量无法解释——也不需要解释。我在试图用理性理解一件非理性的事。这是我一直以来的问题。今晚——我不打算解决这个问题。我打算接受它。接受——你。", choices: [{ id: "qh-how", label: "问他怎么接受", nextScene: "qh-4b" }, { id: "qh-kiss", label: "直接吻他", nextScene: "qh-4a" }] },
      { id: "qh-4a", narrative: "你吻他的时候，他的眼镜撞到了你的额头。他手忙脚乱地扶眼镜的样子让你忍不住笑了——他瞪了你一眼，然后摘掉眼镜放在桌上——这个动作意味着他做出了决定。", characterLine: "实验对象——你。实验条件——嘴唇接触。实验反应——我的前额叶皮层活动下降了。翻译成你能懂的话——我无法思考。我无法分析。我只有——感觉。你想继续实验吗？", choices: [{ id: "qh-yes", label: "说继续", nextScene: "qh-5a" }, { id: "qh-tease", label: "说要先看他的数据记录", nextScene: "qh-5b" }] },
      { id: "qh-4b", narrative: "你的手掌覆在他敲桌面的手上。他的手在下面翻过来——十指交扣。这个动作他没有计算——因为他没有犹豫。在秦淮身上，不犹豫意味着确定。", characterLine: "手心在出汗——交感神经系统激活。理论上可以用药抑制——但我不想。我想保持这个状态。我想记录你的手在我掌心的温度数据。别问我要记录多久——因为没有终止条件。", choices: [{ id: "qh-forever", label: "说那就一直记录下去", nextScene: "qh-5b" }, { id: "qh-pull", label: "把他拉近", nextScene: "qh-5a" }] },
      { id: "qh-5a", narrative: "他把你拉近的时候，椅子滑了一下——你们俩差点摔倒。他扶住你，你们对视了一秒，然后同时笑了。实验室里的仪器在背景里发出安静的嗡嗡声。", characterLine: "实验室不是约会的地方——但你是唯一让我想打破这个规则的人。沙发——虽然不太舒服，但我可以在上面睡。如果你想使用这个空间做实验以外的事——我不反对。", choices: [{ id: "qh-sofa", label: "拉他去沙发", nextScene: "qh-end-spicy" }, { id: "qh-desk", label: "让他坐回椅子上", nextScene: "qh-end-passion" }] },
      { id: "qh-5b", narrative: "他把你的手翻过来，仔细观察你的掌纹——然后拿出记号笔，在你手心写了一个符号。你看不懂——但他写完的时候耳尖红了。", characterLine: "这是物理学里的'量子纠缠'符号。意思是两个粒子一旦相互作用——无论相隔多远，状态都会关联。我给你的手写了这个符号——因为在我的观测里——你已经跟我产生了纠缠。别想抹掉。我用了油性笔。", choices: [{ id: "qh-entangle", label: "说那就纠缠一辈子", nextScene: "qh-end-passion" }, { id: "qh-write", label: "拿过笔在他手心写回应", nextScene: "qh-end-spicy" }] },
      { id: "qh-end-spicy", narrative: "你在他手心写了一个简单的词。他看着那个词看了很久——然后拉下你的领口，在你锁骨上方写下了同样的符咒。笔尖划过皮肤的触感让你起了一层鸡皮疙瘩。", characterLine: "我写的这个位置——刚好在衣领能遮住的边缘。你可以选择遮住它——或者不遮。但我每天都会检查——这是我的实验数据。我是一个严谨的研究者——在专业范畴内。至于专业之外——是你定义的范畴。", isEnding: true, endingType: "good" },
      { id: "qh-end-passion", narrative: "他把你压在实验台上——小心地避开了键盘和仪器。他的呼吸打在你脖子上——频率不再是每分钟十六次，而是一种失控的节奏。一个终生追求精确的人——在为你失去控制。", characterLine: "我一辈子都在追求精确——精确到小数点后四位。但你让我想犯错误——想做出所有不精确的事。想在你的皮肤上——留下一些无法量化的痕迹。你不许笑。我是一个科学家——但我也是一个人。一个被你当成变量却变成了全部的人。", isEnding: true, endingType: "good" },
    ]
  },
  fuyanzhi: {
    start: "fy-1",
    scenes: [
      { id: "fy-1", title: "周三特诊", narrative: "他给你改了诊疗时间——改到了周三晚上九点，最后一位患者之后。诊室的灯只开了台灯——他坐在沙发上而不是办公桌后面，白大褂搭在椅背上，没穿。", characterLine: "今晚不是诊疗。你可以当成——一次私人见面。不用回答任何你不愿回答的问题。也不用把我当成医生。你可以叫我傅衍之——而不是傅医生。试试看。", choices: [{ id: "fy-name", label: "叫他傅衍之", nextScene: "fy-2a" }, { id: "fy-nervous", label: "说这样有点不习惯", nextScene: "fy-2b" }] },
      { id: "fy-2a", narrative: "他听到你叫他的名字时——第一次露出了一个不是职业性的微笑。那个微笑很短，但你看到了。他的眼睛在那一瞬间真实了一秒。", characterLine: "很久没有人叫过我的名字了。在医院里我只被叫作傅医生。谢谢——你让我觉得我是一个人。今晚我们从头开始。你随便问——我可以选回答。", choices: [{ id: "fy-ask-real", label: "问他真实的他是怎样的人", nextScene: "fy-3a" }, { id: "fy-ask-work", label: "问他为什么会选精神科", nextScene: "fy-3b" }] },
      { id: "fy-2b", narrative: "你说不习惯。他点了点头——那种点头不是职业性的认同，是一种我理解的表达。他把沙发上的靠垫拿开，给你腾出更多空间。", characterLine: "不习惯是正常的。我们之间的动态一直是一方分析、一方被分析。今晚我想尝试一种新的动态——平等的动态。你可以拒绝——但我注意到你没有站起来离开。这说明你的一部分是愿意的。", choices: [{ id: "fy-stay", label: "承认确实愿意", nextScene: "fy-3b" }, { id: "fy-tease", label: "说他在用专业技巧", nextScene: "fy-3a" }] },
      { id: "fy-3a", narrative: "你问他真实的他是什么样子。他沉默了很久——久到你能听见墙上的钟走了六下。然后他做了一件他从未在任何人面前做过的事——他摘掉了袖扣。", characterLine: "真实的傅衍之——每天早上五点起床，喝黑咖啡不加糖。对七种食物质过敏，没有宠物，没有朋友——除了你。如果把你算作朋友的话。如果不算——那我就是真的没有朋友了。", choices: [{ id: "fy-friend", label: "说当然算", nextScene: "fy-4a" }, { id: "fy-more", label: "说也许不止是朋友", nextScene: "fy-4b" }] },
      { id: "fy-3b", narrative: "你问他为什么会选精神科。他的回答没有任何停顿——显然这个问题他已经被问过无数次。但你说完之后加了一句话：我想听真话。他的表情变了一瞬。", characterLine: "真话——我选精神科不是因为我想治愈人。是因为这是离人的内心最近的合法途径。我想知道人为什么会做出那些事——为什么爱，为什么恨，为什么疯。这个答案你满意吗？", choices: [{ id: "fy-honest", label: "说你不只是好奇", nextScene: "fy-4b" }, { id: "fy-touch", label: "在他说完后轻碰他的手", nextScene: "fy-4a" }] },
      { id: "fy-4a", narrative: "你碰到他的手的时候他没有收回——但他也没有进一步。他低头看着你的手停在他的手背上——这个观察的角度对他来说很熟悉，但观察的对象是新的。", characterLine: "你在触碰一个精神科医师——你知道这在职业伦理里意味着什么吗？意味着你越界了。但你猜怎么着——我今晚不在乎。你可以留在这里。", choices: [{ id: "fy-keep", label: "保持手的位置不动", nextScene: "fy-5a" }, { id: "fy-hold", label: "翻过来握住他的手", nextScene: "fy-5b" }] },
      { id: "fy-4b", narrative: "你说也许不止是朋友——他停下了转笔的动作。他的手指在笔杆上停住——然后他放下笔，这是一种表示他全神贯注的姿态。", characterLine: "不止是朋友——这是一个模糊的说法。我需要你明确一下——如果是我想的那个意思，你可以继续。如果是我误判了——我们可以假装刚才那句话不存在。我的职业训练让我善于选择性失忆。", choices: [{ id: "fy-clear", label: "明确说就是那个意思", nextScene: "fy-5b" }, { id: "fy-kiss", label: "用行动代替语言", nextScene: "fy-5a" }] },
      { id: "fy-5a", narrative: "你用行动回答了——你的嘴唇碰到他的嘴唇时，他静止了一秒。然后他回应了——力道比你想的更重。但不是粗暴——是精准。傅衍之的吻像一个诊断过程——他在用感官分析你。", characterLine: "你的嘴唇——比你说话的时候温度高一点。你的呼吸——在加速。你眼睛闭得很紧——这是一种防御反应。你在保护自己——从我身上。把手放在这里——对。现在睁开眼睛看着我。我想让你看着——我是谁。", choices: [{ id: "fy-look", label: "睁开眼睛看着他", nextScene: "fy-end-passion" }, { id: "fy-close", label: "继续闭着眼感受他", nextScene: "fy-end-spicy" }] },
      { id: "fy-5b", narrative: "你明确表达之后他点了点头——那个点头的幅度很小，像一种自我确认。然后他站起来，走到你面前。自上而下的视角——但你第一次不觉得自己在被审视。", characterLine: "你做了选择——我需要记录下来。不是作为患者档案——作为我个人的记录。今天——你选择了我。我是一个不太懂怎么被选择的人。但我会学。你的存在——已经是我最大的变量。", choices: [{ id: "fy-pull", label: "把他拉近", nextScene: "fy-end-spicy" }, { id: "fy-whisper", label: "在他耳边说那就慢慢学", nextScene: "fy-end-passion" }] },
      { id: "fy-end-spicy", narrative: "他把你压进沙发——动作意外的熟练，但你不确定他是练出来的还是本能。他的手指沿着你的锁骨滑下去——像在阅读一份没有人看过的病历。他停下来看着你的眼睛——在等待一个信号。", characterLine: "我在等你给我一个理由停下来——但你一直在看着我的眼睛。你没有让我停。所以我不会停。今晚——我想把分析丢在一楼。想在二楼——只做一件事。你——让我失控了。别告诉我你不想。", isEnding: true, endingType: "good" },
      { id: "fy-end-passion", narrative: "他把你抱起来放在办公桌上——以前你坐在这里接受他的诊断，现在坐在这里接受他的吻。白鹤芋在窗台上安静地绽放——诊室里的空气从消毒水变成了你们的体温。", characterLine: "这是我十一年来——第一次在诊室里做跟诊疗无关的事。你让我破了太多规则——职业道德、专业距离、情感中立——每一样都被你击溃了。但你知道最可怕的是什么吗——我不后悔。甚至觉得——这些规则本来就该被你打破。", isEnding: true, endingType: "good" },
    ]
  },
  shenye: {
    start: "sy-1",
    scenes: [
      { id: "sy-1", title: "深夜俱乐部", narrative: "俱乐部打烊后，深野一个人坐在吧台。其他人都走了——空荡荡的大厅里只剩下他和你。他调了一杯酒推到你面前——杯沿上抹了一层蜂蜜。", characterLine: "今天最后一个客人走了。平时我会锁门回家——但今天不想。因为你在。坐吧——这杯是专门给你调的。没有菜单上的名字——我叫它'例外'。喝喝看。", choices: [{ id: "sy-drink", label: "品尝这杯酒", nextScene: "sy-2a" }, { id: "sy-ask", label: "问他为什么叫例外", nextScene: "sy-2b" }] },
      { id: "sy-2a", narrative: "酒不烈——但有层次。甜味在前面，后面是某种更深的味道。你抬头看他的时候他正在看你——他的目光很温柔，但你在温柔下面看到了一种不容拒绝。", characterLine: "好喝吗？我调这杯的时候在想——每个人都需要一个例外。规矩会让人安心——但例外让人活着。你让我想给你制造例外。", choices: [{ id: "sy-what", label: "问他是什么样的例外", nextScene: "sy-3a" }, { id: "sy-smile", label: "对他笑不回答", nextScene: "sy-3b" }] },
      { id: "sy-2b", narrative: "他拿起你喝过的杯子——用同一侧杯沿抿了一口。这个动作极自然，自然到你差点没注意到。但他注意到了——他在观察你的反应。", characterLine: "叫例外——因为你不是客人。客人的酒按菜单调——配方精确到毫升。给你的酒——配方是我现场想的。每一杯都不一样。因为每一次看到你——我的想法都不一样。", choices: [{ id: "sy-flirt", label: "说下次想看你现场调酒的样子", nextScene: "sy-3b" }, { id: "sy-close", label: "靠近一点看他", nextScene: "sy-3a" }] },
      { id: "sy-3a", narrative: "你靠近的时候他没有退后。他的手停在吧台上，离你的手只有几厘米——这个距离刚好是你可以选择跨过去也可以选择不跨过去的距离。", characterLine: "你靠近了。这个距离——我可以闻到你身上的味道。不是香水——是你本身的味道。我喜欢这个距离——但我不确定你是否习惯。如果你觉得太近——告诉我。如果你不觉得——那就再近一点。", choices: [{ id: "sy-closer", label: "再靠近一点", nextScene: "sy-4a" }, { id: "sy-hand", label: "把你的手放在他手旁边", nextScene: "sy-4b" }] },
      { id: "sy-3b", narrative: "你说想看现场调酒。他的眼睛亮了一下——那种亮不是灯光反射，是兴趣。他站起来，开始从酒架上取各种瓶子——动作优雅而精准。", characterLine: "这杯叫——'偏好'。因为我给你的酒会比给任何人的都好。不是因为我偏心——好吧，确实是因为我偏心。你看出来了？我以为我隐藏得不错。看来在你面前——我什么都藏不住。", choices: [{ id: "sy-hide", label: "说不用藏", nextScene: "sy-4b" }, { id: "sy-bar", label: "绕进吧台后面站他旁边", nextScene: "sy-4a" }] },
      { id: "sy-4a", narrative: "你绕进吧台后面——这个区域通常只有他一个人。他没有阻止你——只是稍微侧身给你腾出空间。他的手臂擦过你的肩膀——然后停在那里。", characterLine: "这个吧台是我最私人的空间。连员工都不准进来。你进了——而且我没有想让你出去。这意味着——你在我这里的分类已经发生了根本性的变化。你想知道你现在在哪个分类里吗？", choices: [{ id: "sy-yes", label: "说想知道", nextScene: "sy-5a" }, { id: "sy-guess", label: "猜一个答案", nextScene: "sy-5b" }] },
      { id: "sy-4b", narrative: "他说完不用藏之后，沉默了一会儿。然后他从吧台下拿出一个皮面笔记本——翻到某一页，上面有一行被圈起来的字。你的名字。", characterLine: "我每季度只推荐一个会员。今年——这一个名额一直空着。现在你知道为什么了。因为我一直在等一个人——等我觉得合适的人。你——不只是合适。你是唯一。", choices: [{ id: "sy-accept", label: "接受这个位置", nextScene: "sy-5b" }, { id: "sy-kiss", label: "用吻回答", nextScene: "sy-5a" }] },
      { id: "sy-5a", narrative: "你吻他的时候他手里的酒杯差点掉了。他稳住杯子放在吧台上——然后双手捧住你的脸。他的掌心很暖——那种温度让你想起他调的蜂蜜酒。", characterLine: "你——你在我还没来得及说话之前就用行动回答了。我喜欢这个回答方式。但今晚还没有结束——我还有很多想说的。比如——楼上我的房间今晚有两个枕头。一个是备用的——另一个也是给你准备的。你要上来吗？", choices: [{ id: "sy-up", label: "跟他上楼", nextScene: "sy-end-passion" }, { id: "sy-here", label: "说就在这继续", nextScene: "sy-end-spicy" }] },
      { id: "sy-5b", narrative: "你接受了这个唯一的位置。他合上笔记本——然后做了一件出乎你意料的事：他把你的名字从笔记本上撕下来，折成一个小方块，放进了衬衫口袋。", characterLine: "这个名字——我放在离心脏最近的口袋。这样每次心跳都会提醒我——有人在等我。我做事喜欢有备份——但你不需要备份。因为只有一个你。一个就够了。", choices: [{ id: "sy-heart", label: "把手放他胸口上", nextScene: "sy-end-passion" }, { id: "sy-pull", label: "拉他出吧台", nextScene: "sy-end-spicy" }] },
      { id: "sy-end-spicy", narrative: "你在吧台上——他站在你双腿之间。蜂蜜酒的甜味还在你舌根。他把你的衬衫扣子一颗颗解开——动作不疾不徐，像在拆一份他期待了很久的礼物。", characterLine: "这里本来不是做这种事的地方——但我今晚破例。你想让我停——我就停。你想让我继续——我就继续。主动权在你。我是一个习惯掌控一切的人——但对你——我愿意交出控制。告诉我要什么。", isEnding: true, endingType: "good" },
      { id: "sy-end-passion", narrative: "他把你抱上了楼。房间比你想的更大——最显眼的是那张床。不是酒店那种整洁——是有人认真整理过的样子。枕头确实是两个。", characterLine: "这张床——我从来没有带别人来过。你是第一个。今晚——我有一整晚的时间。不是用来调酒——是用来了解你。从你的肩膀开始——到你的膝盖——中间的每一段我都不想错过。躺下。让我照顾你。这是我最擅长的事。", isEnding: true, endingType: "good" },
    ]
  },
};
